language: node_js
branches:
  only:
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - cd client/site && npm test
after_success:
  - cd client/site && yarn && yarn build