language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - cd client/site && yarn && yarn build
after_success:
  - cd client/site && npm test